[tabcolor]
grid          ansible_host=192.168.0.122
oracle        ansible_host=192.168.0.240
tron          ansible_host=192.168.0.2
batcomputer   ansible_connection=local
low-ones      ansible_host=45.4.172.124 ansible_port=7822

[tabcolor:vars]
ansible_user=lowone
